### ISSUE TITLE
Create Scheme users page 

### ISSUE THREAD

**Issue by CrisSevilleja** [BiologicalRecordsCentre/ABLE#403]
Under Scheme admin create the Scheme user page to sort information of users of a scheme. Similar to Scheme sites: https://butterfly-monitoring.net/scheme-sites

Include the variables:
- Name of the user
- Email of the user
- Sites (number of transect sites)
- Number of samples
- Number of samples this year
- Training mode (active or not) 

Include a searching option at the top of every variable like in the All sites page https://butterfly-monitoring.net/all-sites
National coordinators need this page to track better their users and transects. If possible add the possibility to download the table generated on csv

**Comment by DavidRoy** [comment]
@andrewvanbreda could you pick this issue up.  It is similar to discussions with the FitCounts.  For this report, it can be restricted to country geographic boundaries and users with data within the boundary.

**Comment by andrewvanbreda** [comment]
@JimBacon 
Ok thanks for the feedback, that is the other problem, not quite sure who to ask.

@Gary-van-Breda 
Same question above I guess then.

**Comment by DavidRoy** [comment]
@andrewvanbreda I think we should keep this simple in the first instance.  All the reports can be based on recording activity, e.g.
Number of samples recorded
Number of locations recorded (location-type = transects)

Your approach to training on/off is also fine

This page is only really to give an overview to the co-ordinators and to enable contact

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy 
OK thanks for these answers. 
Given what you say here, that I will display a count of actual recorded transects, then I don't need Gary's answer to finish the report if done this way (although I will ask him the original question another time for curiosity).

**Comment by andrewvanbreda** [comment]
@BirenRathod
Could you pull this report whenever you can thanks
projects/ebms/ebms_scheme_users_sample_details.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda That report has gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren :)

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Could you pull this report again whenever you get a chance please, thanks.

projects/ebms/ebms_scheme_users_sample_details.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda This and one of npms reports have gone live now.

**Comment by DavidRoy** [comment]
@andrewvanbreda ABLE is the project that proceeded SPRING.  We still use the github repository as there are remaining issues.  For the Transect issue, I suggest raising in the ABLE repo.  At the end of SPRING, I'll reconsider where to manage issues across the pollinator and butterfly monitoring work.

I'll look at the user report now, thanks

**Comment by CrisSevilleja** [comment]
The scheme user page looks good to me, thank you @andrewvanbreda for making it. I am happy to see it on live when David checks it.

**Comment by DavidRoy** [comment]
@andrewvanbreda I can't get the report to show the email addresses.  I set this user with editor rights for website = EBMS.  (http://warehouse1.indicia.org.uk/index.php/user/edit_from_person/230588)

on the ebms drupal site, user is: https://butterfly-monitoring.net/index.php/user/1198

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy

I have looked at this.
It isn't a setup issue, your understanding of how to set this up is correct.
It also works fine on my machine.
I believe it is a bug in the report, that is causing it to work on my machine because I created all the data myself.
Looking at the reports on the system, we have never had report similar to this using this email access check, so I think the logic in the report is a bit wrong.
It is complex though, so I will need to debug it when my brain is in the right mode, n middle of something else right this second, but I will get onto it when I can.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod
Whenever you get a chance during the week, could you pull this report please. Thanks
reports/projects/ebms/ebms_scheme_users_sample_details_2.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda That report gone live now.

**Comment by CrisSevilleja** [comment]
@andrewvanbreda the page is working well, I can select the columns to sort the users and it works, quite useful. The email is not appearing, not urgent to have but good to have it at a certain moment. The only thing that is wrong is the table of users appears twice on the page if you can remove one. Thank you for creating this functionality :)

**Comment by andrewvanbreda** [comment]
Hi @CrisSevilleja 
Yes the 2 grids were deliberate due to me debugging the code.
The page is still under testing and debugging due to the email problem which is still present.
Do not use the page for any serious work yet until it has been confirmed as working, you may look at the data if you wish, but do not assume it is correct until I can confirm all problems have been fixed.

**Comment by andrewvanbreda** [comment]
Hi @BirenRathod 
Um.....am confused what is going on here, would you be able to run this code please and send me result. Cheers

  SELECT p.id, accesscheck.id,accesscheck.user_id, accesscheck.website_id, accesscheck.site_role_id
  FROM indicia.locations l
    JOIN indicia.locations_websites lw on lw.location_id = l.id
    JOIN indicia.location_attribute_values lav on lav.location_id = l.id
      AND lav.location_attribute_id = 233
      AND lav.int_value = 84
      AND lav.deleted=false
    JOIN indicia.cache_samples_functional csf on csf.location_id = l.id
      AND csf.survey_id=562
    JOIN indicia.users u on u.id = csf.created_by_id
    JOIN indicia.people p on p.id = u.person_id AND p.deleted = false
    LEFT JOIN indicia.users_websites accesscheck on accesscheck.website_id=lw.website_id
      AND accesscheck.user_id=227047 AND accesscheck.site_role_id < 3
    WHERE l.deleted = false
      AND l.location_type_id in (777);

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy @BirenRathod 
Would you be able to run these 4 queries please, and send me results with an indiciation which result is for which query please. Thank you.

SELECT p.id, accesscheck.id,accesscheck.user_id, accesscheck.website_id, accesscheck.site_role_id
FROM indicia.locations l
JOIN indicia.locations_websites lw on lw.location_id = l.id AND lw.website_id=118
JOIN indicia.cache_samples_functional csf on csf.location_id = l.id
AND csf.survey_id=562
JOIN indicia.users u on u.id = csf.created_by_id
JOIN indicia.people p on p.id = u.person_id AND p.deleted = false and p.id = 336040
LEFT JOIN indicia.users_websites accesscheck on accesscheck.website_id=lw.website_id
AND accesscheck.user_id=227047 AND accesscheck.site_role_id < 3
WHERE l.deleted = false
AND l.location_type_id in (777);

SELECT p.id, accesscheck.id,accesscheck.user_id, accesscheck.website_id, accesscheck.site_role_id, count (csf.id)
FROM indicia.locations l
JOIN indicia.locations_websites lw on lw.location_id = l.id AND lw.website_id=118
JOIN indicia.cache_samples_functional csf on csf.location_id = l.id
AND csf.survey_id=562
JOIN indicia.users u on u.id = csf.created_by_id
JOIN indicia.people p on p.id = u.person_id AND p.deleted = false and p.id = 336040
LEFT JOIN indicia.users_websites accesscheck on accesscheck.website_id=lw.website_id
AND accesscheck.user_id=227047 AND accesscheck.site_role_id < 3
WHERE l.deleted = false
AND l.location_type_id in (777)
GROUP BY p.id, accesscheck.id;

SELECT p.id, accesscheck.id,accesscheck.user_id, accesscheck.website_id, accesscheck.site_role_id
FROM indicia.people p
JOIN indicia.users u on u.person_id = p.id AND u.deleted = false
JOIN indicia.users_websites uw on uw.user_id = u.id AND uw.website_id=118
JOIN indicia.cache_samples_functional csf on csf.created_by_id = u.id
AND csf.survey_id=562
JOIN indicia.locations l on l.id = csf.location_id AND l.location_type_id = 777 AND l.deleted=false
LEFT JOIN indicia.users_websites accesscheck on accesscheck.website_id=uw.website_id
AND accesscheck.user_id=227047 AND accesscheck.site_role_id < 3
where p.id = 336040;

SELECT p.id, accesscheck.id,accesscheck.user_id, accesscheck.website_id, accesscheck.site_role_id, count (csf.id)
FROM indicia.people p
JOIN indicia.users u on u.person_id = p.id AND u.deleted = false
JOIN indicia.users_websites uw on uw.user_id = u.id AND uw.website_id=118
JOIN indicia.cache_samples_functional csf on csf.created_by_id = u.id
AND csf.survey_id=562
JOIN indicia.locations l on l.id = csf.location_id AND l.location_type_id = 777 AND l.deleted=false
LEFT JOIN indicia.users_websites accesscheck on accesscheck.website_id=uw.website_id
AND accesscheck.user_id=227047 AND accesscheck.site_role_id < 3
where p.id = 336040
GROUP BY p.id, accesscheck.id;

**Comment by DavidRoy** [comment]
@BirenRathod are you ok to run these?

**Comment by BirenRathod** [comment]
@DavidRoy Yes, that is fine. I'm on the server now.

**Comment by BirenRathod** [comment]
@andrewvanbreda I have attached the results here. File names are in same order as you posted the query above.
[ABLE.zip](https://github.com/BiologicalRecordsCentre/ABLE/files/10784260/ABLE.zip)

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks. I will have to examine these before commenting further.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks for those results, although they don't makes sense, they suggest the system should be working.

I have tried to re-order the report code in an attempt to fix this, but if it doesn't work think I will have to revisit this.

Could you pull this report please, thanks
projects/ebms/ebms_scheme_users_sample_details_3.xml

**Comment by BirenRathod** [comment]
@andrewvanbreda That report gone live now.

**Comment by andrewvanbreda** [comment]
@BirenRathod 
Thanks Biren, am going to revisit this, as the email still isn't working. I think actually there is something automatic going on with the parameters which is overriding what I am trying to do.

@DavidRoy @CrisSevilleja 
I have changed the report and it is giving exactly the same results which is a good sign. That added to my previous testing means that, despite the email problem, I believe the data to be correct.
Note the report only returns data for survey 562 (EBMS Transects), if it is supposed to be returning anything else you'll have to let me know.
I will have to return to the email problem another time.

**Comment by CrisSevilleja** [comment]
I think for the moment is enough, I am sure when I present this new function to the coordinators they will have suggestions to improve this page but for the moment I am happy with it. 

I will write on the page the table will show only information regarding transects. Thank you for making this available, when this page places under Scheme admin I will announce it to coordinators. 

Leave the issue open to solve the email problem. thanks

**Comment by DavidRoy** [comment]
Thanks @CrisSevilleja 
@andrewvanbreda - can you make the page available under the scheme admin menu, restricted to users with the 'scheme co-ordinator role'

**Comment by andrewvanbreda** [comment]
@DavidRoy @CrisSevilleja 
I have done this now.
I have hidden the email column until I can work out is happening with that problem.

I did just think of something. As it is a sample report, and as the samples training flag is a relatively new function (it used to be that only occurrences were marked as training, not the sample), it is possible that the report might show some data as being non-training when it is training.
In fact I would say that is likely.
There is nothing I can do about it as it would be a data problem rather than a reporting problem.
These is another issue open somewhere on another project which relates to addressing this.

**Comment by CrisSevilleja** [comment]
Thank you @andrewvanbreda I see now this page on the menu of eBMS. 

when we are releasing this page to coordinators, I am sure there will be questions on how to change training samples to normal samples because sometimes people put it on their account and forget to remove it... So, we need to track this in another issue separately. 

However, the problem you describe I think you mentioned here #515 
Indeed it is something to be checked in the code if there are non-training records when they are training.

**Comment by andrewvanbreda** [comment]
@CrisSevilleja 
Yes that Github issue is related to this. There is also one open on another project related to app behaviour in relation to this.
I have it on my list of work to check the training behaviour of the EBMS site as part of that issue that you linked to there.
If we do identify issues with this such as people setting the checkbox incorrectly,  I can change the sample in the user interface we have for the database (Warehosue UI), this acts a bit like a website where data can be changed by clicking checkboxes. If it is lots of data, I will need to change this in the database directly using a script.

**Comment by DavidRoy** [comment]
Closing as the original issue is fixed?

**Comment by CrisSevilleja** [comment]
@andrewvanbreda Thinking about this page for coordinators, I realised this page is not available for coordinators. The page is live on eBMS but not related to the coordinator role. Could you make this possible? thank you in advance

**Comment by DavidRoy** [comment]
@Gary-van-Breda best for you to pick this one up?

**Comment by andrewvanbreda** [comment]
Hi @DavidRoy @Gary-van-Breda 
Something strange going on here.
I just tried some very obvious things that haven't worked.
(added Indicia Data View permission to scheme coordinator, also rebuild permissions cache. I also went to the menu settings and told the system to show the menu option explicitely for admins and scheme co-ordinators).
The menu still isn't showing even though actually Scheme Coordinators can go to the URL directly just fine.
https://butterfly-monitoring.net/scheme-users-information

If you need me to work on it let me know, although probably wouldn't be today.

**Comment by Gary-van-Breda** [comment]
There was something very strange with that particular menu link, related to translations - the link was to specifically the English translation and had no language associated with it.
I have created a new link which matches the format of the other links, and set the roles up as above (admins and scheme co-ordinators), and deleted the old one.
The link now appears in the menu for the scheme coordinators (I've masqueraded as a couple to check).

@CrisSevilleja Can you check if you are happy?

**Comment by CrisSevilleja** [comment]
thank you! The page is working well for coordinators and providing all the information I asked. Happy to close it.
Just to confirm, this page is only related to transect sites, nothing to do with other surveys 15min counts or moth traps.
