### ISSUE TITLE
Wrong species name in 15 min counts

### ISSUE THREAD

**Issue by chrisvanswaay** [BiologicalRecordsCentre/ABLE#520]
My colleague @JurrienVanDeijk is now on the Canaries, and I noticed he reported Euchloe charlonia from Tenerife, which would be a new species for the island. So quite a spectacular find, but when I congratulated him via whatsapp he said he didn't see that species.
These is a screenshot of one of his 15 min counts with that species:
![image](https://user-images.githubusercontent.com/25886005/216267116-d64a1232-a78d-42b6-8d60-7c9608bc7146.png)

I tried this morning myself, and entered via the app three species:
1 Pontia daplidice (resedawitje)
2 Euchloe charlonia (groen marmerwitje)
3 Euchloe eversi
Here a screenshot of my phone:
![image](https://user-images.githubusercontent.com/25886005/216267481-726be9f3-2245-4f9e-be07-b95f21fdd672.png)

Then I went to the website, and this what is to be seen there:
![image](https://user-images.githubusercontent.com/25886005/216267584-5a075243-88d1-4700-a168-3dcf15058171.png)

As you can see the name of the two Euchloe charlonia (groen marmerwitje; greenish black-tip) has now changed to two Euchloe bazae (spaans marmerwitje, Spanish Greenish Black-tip).

I'm not sure what is wrong where, but of course what you enter should end up in the database and in the download. Hope this can be corrected.

**Comment by chrisvanswaay** [comment]
@DavidRoy @kazlauskis @JimBacon

**Comment by kazlauskis** [comment]
You have entered  **Groen Marmerwitje** which you say should be _Euchloe charlonia_. In the app **Groen Marmerwitje** is synonym to _Euchloe bazae_. So this needs to be corrected in the database.

@JimBacon Here is what I get in the app when I run `reports/projects/ebms/taxa_list_for_app.xml`

```JSON
        {
            "id": "552346",
            "taxon_group": "insect - butterfly",
            "taxon": "groen marmerwitje",
            "language_iso": "nld",
            "preferred": "f",
            "parent_id": "432039",
            "external_key": "eBMS258",
            "preferred_taxa_taxon_list_id": "432240",
            "preferred_taxon": "Euchloe bazae",
            "attr_id_taxa_taxon_list_194": null,
            "attr_taxa_taxon_list_194": null
        }
```

**Comment by chrisvanswaay** [comment]
And there is something else wrong leading to another species entered by @JurrienVanDeijk to appear on the website as Euchloe charlonia. Jurriën is now travelling for holidays, so he can't test this himself. But something else ended up as E charlonia in his observaitons on Tenerife.

**Comment by chrisvanswaay** [comment]
Maybe there is a mistake in the list with Dutch vernacular names I uploaded some months ago. I was a list someone gave to me, but I haven't checked all names (actually I don't know the Dutch names of many species outside NL). Does one of you still have that list, or can generate a list, @kazlauskis or @JimBacon ? Are these lists different in the web and in the app?

**Comment by JimBacon** [comment]
Hi @chrisvanswaay 
The list of Dutch butterfly names is here. https://github.com/BiologicalRecordsCentre/ABLE/issues/366#issuecomment-1218126816
On line 38 it gives groen marmerwitje  as the name for _Euchloe bazae_

**Comment by chrisvanswaay** [comment]
OK, that's where the mistakes were. I don't notice such mistakes, as I usually use the scientific name. I have now adapted these names, this should be ok (at least for the Euchloe species). 

[European.checklist.Dutch.vernacular.names_v2_20230202.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/10567347/European.checklist.Dutch.vernacular.names_v2_20230202.xlsx)

**Comment by chrisvanswaay** [comment]
That means that what @JurrienVanDeijk  entered as Canarisch marmerwitje and entered in the database as Euchloe charlonia should be changed to Euchloe eversi (Tenerife gestreept marmerwitje). Should he do that himself?

**Comment by chrisvanswaay** [comment]
Just noticed more mistakes, will make an update of the complete list.

**Comment by JimBacon** [comment]
Comparing the two files, I have made changes to vernacular names in the database as follows:

Modified
_Euchloe bazae_ (id = 432240) from  **groen marmerwitje** (id = 552346) to **Spaans groen marmerwitje** (id = 571810)
_Euchloe charlonia_ (id = 432238) from **canarisch marmerwitje** (id = 552347) to **groen marmerwitje** (id = 571811)

Added
_Euchloe hesperidum_ (id = 432232), **Fuerteventura gestreept marmerwitje** (id = 571812)
_Euchloe eversi_ (id = 432230), **Tenerife gestreept marmerwitje** (id = 571813)
_Euchloe grancanariensis_ (id = 432231), **Gran Canaria gestreept marmerwitje** (id = 571814)

I used the warehouse website interface to do this and it marked as deleted the old names which were wrong. This means I can update the sightings with the correct species provided I understand correctly what is needed.

@chrisvanswaay does the following sound correct? 

- Records made of **groen marmerwitje** (id = 552346), appearing as _Euchloe bazae_ (id = 432240) should be changed to **groen marmerwitje** (id = 571811) and appear as _Euchloe charlonia_ (id = 432238)

- Records made of **canarisch marmerwitje** (id = 552347), appearing as _Euchloe charlonia_ (id = 432238) should be changed to **Tenerife gestreept marmerwitje** (id = 571813) appearing as _Euchloe eversi_ (id = 432230). This is an assumption based on the fact Jurrien was on Tenerife.
 
We can expect further erroneous records until the app can be updated.

**Comment by chrisvanswaay** [comment]
@JimBacon Yes, that looks correct to me. I have reviewed the complete specieslist and found quite a few errors, and in some cases names have changed as a species has 
[European.checklist.Dutch.vernacular.names_v3_20230202.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/10569607/European.checklist.Dutch.vernacular.names_v3_20230202.xlsx)
been split. Attached an updated version, which has all the names of the species on the European RL (which is the list of Wiemers etal 2019), extended with a few species from adjacent areas as some Spanish enclaves in N Morocco.

**Comment by JimBacon** [comment]
Hi @chrisvanswaay 

When I open the file above I have a problem with some unusual looking characters. E.g.
_Maniola halicarnassus_, ege‹sch bruin zandoogje
_Euphydryas desfontainii_, moza?ekparelmoervlinder
_Erebia rondoui_, pyrenee‰nglanserebia

Can you check to see whether you have this problem please. If yes, can you correct these and other similar. If no, I have to figure out the character encoding.

**Comment by chrisvanswaay** [comment]
Sorry, I thought I dealt with them. Hope this is now correct.
[European.checklist.Dutch.vernacular.names_v3_20230202.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/10570233/European.checklist.Dutch.vernacular.names_v3_20230202.xlsx)

**Comment by chrisvanswaay** [comment]
What a horrible language we have with all these funny characters. Anyway, corrected that one too.
[European.checklist.Dutch.vernacular.names_v3_20230202.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/10571013/European.checklist.Dutch.vernacular.names_v3_20230202.xlsx)

**Comment by JimBacon** [comment]
Language is beautiful, it's the computers that are the problem! 
And actually the computers don't need to cause problems any more if only they all used UTF-8 encoding.

Another error in the spreadsheet which we corrected previously:  _Polyommatus celina_ should be **mediterraan icarusblauwtje** with the double r in mediterraan.

**Comment by JimBacon** [comment]
This is work in progress. 

Added 
_Aricia montensis_ (432344), iberisch vals bruin blauwtje
_Boloria alaskensis_ (432398), toendraparelmoervlinder
_Boloria angarensis_ (432414), bosbesparelmoervlinder
_Boloria selenis_ (432410), siberische parelmoervlinder
_Boloria tritonia_ (432401), steenbreekparelmoervlinder
_Callophrys chalybeitincta_ (432271), oostelijk groentje
_Callophrys suaveola_ (432269), berggroentje
_Chazara persephone_ (432541), donkere heremiet
_Cigaritis acamas_ (432261), oostelijke zilverstreep
_Coenonympha amaryllis_ (432468), veelooghooibeestje
_oenonympha phryne_ (432461), geaderd hooibeestje
_Erebia cyclopius_ (432573), cyclooperebia

Not added as absent in EBMS list
_Deudorix livia_, granaatappelpage

@chrisvanswaay , Does _Boloria oscarus_, **oscars parelmoervlinder** want an apostrophe like e.g. **freija's parelmoervlinder**?

It is dawning on me that these are mostly additions rather than corrections and I can  separate them out in to a file I can upload. Others will still need individual attention to resolve. I will pick this up again in a week's time.

**Comment by chrisvanswaay** [comment]
Hi @JimBacon , I will check, oscars parelmoervlinder is the name used on observation.org. Would be good if the names are the same. And indeed it should be mediterraan blauwtje, good you noticed that.

**Comment by JimBacon** [comment]
As discussed previously (See https://github.com/BiologicalRecordsCentre/ABLE/issues/366#issuecomment-1260812230), I am removing from the spreadsheet species which are not present in the EBMS list. These are

1.  The 30 African species  
2.  _Polyommatus eleniae_, _Polyommatus galloi_, _Polyommatus gennargenti_ which are not considered species any more.
3.  _Melitaea nevadensis_ which is now called _Melitaea celadussa_ and already in the list
4.  _Hipparchia occidentalis_ which is now lumped with _H azorina_ and already in the list

In addition I propose removing _Spialia ali_, another African species which has appeared.

This leaves me 2 species where I need advice @chrisvanswaay 

1. _Deudorix livia_ which is not currently in the EBMS list. Shall I add this?
2. _Euphydryas beckeri_ which is in the EBMS list as the subspecies, _Euphydryas aurinia beckeri_. Do you want this added as a species and have the subspecies removed from future use? There are  23 records for _Euphydryas aurinia beckeri_ which could either remain linked to the subspecies name, as that is how they were recorded, or they could be changed to refer to the new name. I have a feeling it is customary to leave them as recorded.

**Comment by chrisvanswaay** [comment]
Hi @JimBacon , the point with the African species is that they had to be added to the European RL as they occur in either Ceuta or Melilla. I also don't understand the reasoning behind this, but EU/IUCN decided this (why not include the Dutch Caribian islands, or French Guyana then?). I don't mind if you exclude them, but that's the reason they are in the list (which came from the RL). And indeed _Spialia ali_ is also an African species occurring in one of the two Spanish enclaves.

_Deudorix livia_ has been found on Cyprus and in Greece, I think only one specimen each time. At least this shows this mainly African and Middle East species is capable of getting to Europe.

And I never should have used a list supplied by someone else, as I missed the _E beckeri_ case. Thanks for your consistency checks! At present this is still considered a subspecies of _E aurinia_, so I agree with your suggestion to keep _E aurinia beckeri_ in the list. The Iberian subspecies is clearly different in appearance and biology, but seems not to differ enough in DNA it seems. I leave that to the taxonomists. Sorry for the confusion.

**Comment by JimBacon** [comment]
Thanks @chrisvanswaay. 

My objective here is to attach Dutch vernacular names to the species in the EBMS list. I was omitting the African species because they are not currently in the list. If they need adding then please tell me. Ceuta and Melilla are included in our outline of Spain and are present as NUTS level 2 regions. I suppose it depends on whether the boundaries of the project are political or geographical.

I think you are saying I should add _Deudorix livia_ to the list.

I will leave _Euphydryas aurinia beckeri_ unchanged.

**Comment by DavidRoy** [comment]
@JimBacon just checking on the african names.  We'll need these additions for including Kenya?

**Comment by JimBacon** [comment]
We've already incorporated the Kenyan species (https://github.com/BiologicalRecordsCentre/ABLE/issues/432) so these are additional species present in North Africa.

**Comment by DavidRoy** [comment]
Thanks!

**Comment by JimBacon** [comment]
I've added a further 43 Dutch names which were missing and updated a dozen others. I have one further query for you @chrisvanswaay: in removing the accent from provenciaals bleek blauwtje you have introduced a letter 'i' - is this correct?

id | scientific name | new name | old name
---|---|---|---
432620|Erebia scipio|provencaalse erebia|provençaalse erebia
432347|Lysandra hispana|provenciaals bleek blauwtje|provençaals bleek blauwtje

**Comment by chrisvanswaay** [comment]
Shame on me, as the old names are the right ones (so provençaalse erebia and provenciaals bleek blauwtje). As I never use the Dutch names I simply overlook all these errors. Thanks for clearing it up.

**Comment by JimBacon** [comment]
Thanks @chrisvanswaay, I will leave provençaalse erebia and provençaals bleek blauwtje unchanged.

You nearly caught me out with a couple of name moves. Would you answer the following questions:

- Is _Nymphalis l-album_ (549819) a synonym for _Nymphalis vaualbum_ (432430)?
- Is _Pseudochazara mercurius_ (432549) a synonym for _Pseudochazara williamsi_ (432547)?

Currently they are all in the list as different species.

**Comment by chrisvanswaay** [comment]
@JimBacon 
Indeed _Nymphalis l-album_ (549819) is a synonym for _Nymphalis vaualbum_ (432430), where the latter is the now the valid name. But _Pseudochazara mercurius_ (432549) and _Pseudochazara williamsi_ (432547) are different species, with the first one occurring in S Russia, and the second in S Spain.

**Comment by JimBacon** [comment]
Note. I have added  _Nymphalis l-album_ as a synonym for _Nymphalis vaualbum_ (432430). There was only one occurrence (29354289) made against _Nymphalis l-album_ (549819) so I have updated this to point to the new synonym (571889) and marked the old species record as deleted.

@Karolis, the app can be updated with the revised species names and this issue closed when done (I sincerely hope!).

@chrisvanswaay, for reference, below is the list of dutch names now installed in our database.
[EBMS-dutch-species-names.xlsx](https://github.com/BiologicalRecordsCentre/ABLE/files/10785995/EBMS-dutch-species-names.xlsx)

**Comment by chrisvanswaay** [comment]
Thanks @JimBacon

**Comment by JimBacon** [comment]
@kazlauskis I mis-typed your @ mention above.
Actually, once the app has been updated, please comment here and leave the issue open.
I will need to update any records which have been created with the wrong names as mentioned in https://github.com/BiologicalRecordsCentre/ABLE/issues/520#issuecomment-1413667799

**Comment by kazlauskis** [comment]
@JimBacon I've pulled the latest translations and pushed the app to live now. Leaving this open for you to close.

**Comment by JimBacon** [comment]
Checking for records made against the incorrect taxon names which started this thread.

There are two occurrences made against taxa_taxon_list_id 552346. These are the test records that Chris made.
There are thirty-two occurrences made against taxa_taxon_list_id 552347. These are the records made by Jurrien

The following queries correct the errors
```sql
UPDATE occurrences
SET taxa_taxon_list_id = 571811, updated_on = now(), updated_by_id = 2
WHERE id IN (29267767, 29267768)

INSERT INTO work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
SELECT 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
FROM (VALUES (29267767), (29267768)) AS t(id)

UPDATE occurrences
SET taxa_taxon_list_id = 571879, updated_on = now(), updated_by_id = 2
WHERE id IN (29253438,29253441,29253444,29253445,29253440,29253446,29253449,
	     29253452,29253439,29253442,29253447,29253450,29253453,29253454,
	     29253470,29253471,29253473,29253487,29253455,29253456,29253457,
	     29253458,29253460,29253448,29253461,29253462,29253465,29253468,
	     29253472,29253479,29253480,29253484)

INSERT INTO work_queue(task, entity, record_id, params, cost_estimate, priority, created_on)
SELECT 'task_cache_builder_update', 'occurrence', id, null, 100, 2, now()
FROM (VALUES (29253438),(29253441),(29253444),(29253445),(29253440),
	     (29253446),(29253449),(29253452),(29253439),(29253442),
	     (29253447),(29253450),(29253453),(29253454),(29253470),
	     (29253471),(29253473),(29253487),(29253455),(29253456),
	     (29253457),(29253458),(29253460),(29253448),(29253461),
	     (29253462),(29253465),(29253468),(29253472),(29253479),
	     (29253480),(29253484)) AS t(id)

```
It was discovered that the taxa_taxon_list_id for Tenerife gestreept marmerwitje is now 571879 and not 571813.

**Comment by chrisvanswaay** [comment]
@JimBacon  I fear I have to reopen this one, as a recorder reported the wrong species in his download. It concerns sampleid 22828305, and where - as happened earlier - it goes wrong if someone uses the Dutch name for the Common Blue (Polyommatis icarus), which is icarusblauwtje, and then ends up with Glaucopsyche alexis and common name klöverblåvinge. See screenshot below:
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25886005/ca6cb700-1c4c-4b2f-b771-2f14a6765cf7)

**Comment by chrisvanswaay** [comment]
See also this on the website. When you search for icarusblauwtje, you get both P icarus and G alexis:
![image](https://github.com/BiologicalRecordsCentre/ABLE/assets/25886005/8412b871-7edf-4fef-85a9-f310ab677c8e)

**Comment by chrisvanswaay** [comment]
See also https://github.com/BiologicalRecordsCentre/ABLE/issues/574

**Comment by JimBacon** [comment]
This is #574 still manifesting itself. Until the species list on the app is updated, and users have installed the new version, we will continue to see this happen. Once the app has been fixed I will correct all the problematic species records.

**Comment by kazlauskis** [comment]
That's right. I have updated the species lists in the app, but it will take some time for users to update their apps...

**Comment by chrisvanswaay** [comment]
@kazlauskis  He writes me he has 1.21.0 (261). Is there a newer version he can update to?

**Comment by kazlauskis** [comment]
Not at the moment, but I am working on the next app release, which will have it updated. The v1.21.0 was released on the 8th of June, and the user should have the corrected species list from around that time, so it is strange it is still uploading incorrect records. Can you reproduce this issue?

**Comment by JimBacon** [comment]
Reproduced but posted in #574
