### ISSUE TITLE
constant Butterfly Count App crash on start (CRITICAL!)

### ISSUE THREAD

**Issue by szabadfalvi** [BiologicalRecordsCentre/ABLE#592]
### Describe the issue

When starting the app on Android 12 (MIUI Global 13.0.6.0) on Xiaomi Redmi Note 11, the app constantly crashes with OOM error.
This has happened with me twice before, always on Xiaomi phones, bit it was also reported by 1 other user using Xiaomi phone.
Android versions and Xiaomi models were different: Xiaomi Redmi Note 8T, Xiaomi Redmi Note 8 Pro, Xiaomi Redmi Note 11.
The App always contains a large number uploaded surveys, this time over 200 surveys. Unsent finished surveys (now 10 surveys) are still on the affected phones but no way to salvage them???!!!

### Expected behaviour

Start the app normally without losing your daily work.

### To Reproduce

1. amass couple of hundred surveys and upload them,
2. do some more surveys...
3. try to open the app on a Xiaomi Redmi phone (MIUI on whatever android version).

### App Version

cannot open the app but current Beta version

### Device

Xiaomi Redmi Note 11

### When did this happen

2023.06.17. (and 2 times before in 2022 and 2023)

### Screenshots

![Screenshot_2023-06-17-16-01-42-729_Crash_OOM_StackTrace](https://github.com/BiologicalRecordsCentre/ABLE/assets/93212424/666b3c34-1e76-4012-b0a0-91be6aedd02b)
![Screenshot_2023-06-17-16-02-16-896_Crash_OOM_SystemLog](https://github.com/BiologicalRecordsCentre/ABLE/assets/93212424/469956ab-5af2-4e62-b551-8204ea8c12dd)
![Screenshot_2023-06-17-16-03-20-198_Crash_OOM_EventLog](https://github.com/BiologicalRecordsCentre/ABLE/assets/93212424/2162a379-0081-4b7e-9886-6e221d82b32d)
![Screenshot_2023-06-17-14-25-13-649_Crash_OOM_Screen](https://github.com/BiologicalRecordsCentre/ABLE/assets/93212424/9022df8a-27bb-4e04-bb6c-4b88f526c3ca)

### Additional context

Screenshots of error report attached. 
Main error info: "java.lang.OutOfMemoryError: Failed to allocate a 76309536 byte allocation with 25165824 free bytes and 71MB until OOM, target footprint 218278032, growth limit 268435456 at java.lang.StringFactory.newStringFromChars(StringFactory.java:112)..." etc.
Only Xiaomi phones are affected? >> If yes, problem with MIUI (Xiaomi's Android skin/interface)?
Crash comes after amassing a lot of uploaded and/or pending surveys (200+)?
To fix this recurring crash + develop a salvage app/method is critically important(!) >> debug beta version is needed to pinpoint the exact source of the problem. Memory leak? The app seemingly attempts to put together a very long text string?

**Comment by Vilius-Stankaitis** [comment]
Hi, thank you for this well-defined description! 

We will take a look at this!

**Comment by szabadfalvi** [comment]
Any news on the crash + data salvaging yet?

**Comment by Vilius-Stankaitis** [comment]
I could not reproduce this issue on any of my five devices, which consist of various Android versions and models with 1000 dummy records.  I will implement VirtualScroll as it renders quite slow with so many records.

Since this is a new problem for us, it may take some time to investigate and find a solution. Although there are some suggestions on the forum, we need to conduct additional testing before implementing them.

Have you attempted to clear the cache data on your device? You can do this by going to Device Settings -> ButterflyCount -> Storage -> Clear cache. Additionally, please check how much free space is available on your device.

Have you tried restarting your device? Sometimes a simple reboot can resolve certain issues.

How have you resolved this issue in the past? Did you reinstall the app? I'm curious about the steps you've taken previously to address similar problems.

How many pending records do you have on your device?

**Comment by szabadfalvi** [comment]
"I could not reproduce this issue on any of my five devices, which consist of various Android versions and models with 1000 dummy records. I will implement VirtualScroll as it renders quite slow with so many records. Since this is a new problem for us, it may take some time to investigate and find a solution. Although there are some suggestions on the forum, we need to conduct additional testing before implementing them."  >> OK
 
"Have you attempted to clear the cache data on your device? You can do this by going to Device Settings " >> Yes.
"Additionally, please check how much free space is available on your device." >> Ample (15.8 GB available, 48.2 GB occupied out of the total 64 Gig)
 "Have you tried restarting your device? Sometimes a simple reboot can resolve certain issues." >> Yes. Several times.
"How have you resolved this issue in the past?" >> I could not. 
(1) I still keep one phone untouched with the last but one crashed app, too many valuable unsent surveys. >> waiting to salvage the data.
(2) Once I reinstalled the app.
(3) Another time I reset the aoo which also seemed to work.

First it h ad around 35 (on the Xiaomi Redmi Note 8T) because i was in Croatia and my data roaming due to SIM card problems >> at home the app crashed when wanted to upload them.
The second time around 8-10 i my think (daily work , i have been keen on uploading as soon as possible since the first crash).
The third time around 5-6, i.e. my daily work.
This time 9 finished 15 min counts, (1 was just a test), + 1 draft Moth survey with 8-10 moth pics (a test of the species recognition engine).

Is it possible to root the phone, copy the data on the phone to an Android emulator on PC and give it an "insane" amount of mem to see if it starts up?

Would it help if I send you my former phone with the former crash?

**Comment by Vilius-Stankaitis** [comment]
I am currently conducting tests to improve the computational capabilities of the application. Once the testing phase reaches a suitable stage, I will invite you for internal testing. You will have the opportunity to update your app through the Play Store, and we can thoroughly test whether the changes address the issues present in the app.

**Comment by Vilius-Stankaitis** [comment]
A few questions: 

1. What surveys do you do most of the time? (15min, transect or moth)? 
2. For those 200+ surveys how many photos do they contain approx? 
3. Is your device system up to date (Android, Android web view)
https://thegadgetlite.com/2022/08/xiaomi-apps-crashing-issue-in-miui/ Here is the link to how to update the Android web view.

**Comment by szabadfalvi** [comment]
1. What surveys do you do most of the time? 
>> general 15min count (SPRING moth and , transect  1-2 just for testing)
3. For those 200+ surveys how many photos do they contain approx?
>> a lot.  an average of 5 pics per survey.
NB' Pics handling by the apps is a long standing is issue: >> each pic is stored in 2 folders simultaneously = i.e. essentially duplicated: in Internal storage / Pictures and in the app's android directiry (Internal storage /

**Comment by szabadfalvi** [comment]
1. What surveys do you do most of the time? 
>> general 15min count (transect + moth just 1 or 2 for testing).
2. For those 200+ surveys how many photos do they contain approx? 
>> A lot. An average of 5 pics per survey. >> NB: picture handling by the App is a long standing problem. It stores each pic in two separate directories simultaneously = i.e. duplicates it: Internal shared storage / Pictures and in the App"s folder in Internal shared storage / Android / data / uk.ac.ceh.ebms / files / Pictures (+ the thumbnails). These pic storage folders are not changed even if you moved/put your DCIM dir on the phone's SD card. It eats up the phone's storage space pretty quickly (reaching many gigs) >> what i do: after upload i delete the pics from Internal shared storage / Pictures  >> the app still shows the pics for the already uploaded surveys too >> but i did not do this in case of the first similar crash.
3. Is your device system up to date (Android, Android web view) 
>> yes.
The solution on the link you sent is not working.

**Comment by kazlauskis** [comment]
@szabadfalvi, thanks for the details. We have found the issue here to be a high number of species photo thumbnails stored inside the internal app's SQLite database. We didn't expect this to be an issue, but thousands of small-size images do accumulate in size and apparently stress the database on some devices. We are working on a solution to fix this problem.

Regards your unsent records, do you still have the old app that doesn't open? If you do, we could issue a new app build specifically for you to recover these. This is a bit experimental, but it might be worth a try. Would you be comfortable installing the app as an APK file directly into your device? Alternatively, I could look into options to temporarily host this on the Play Store for you to install.

**Comment by szabadfalvi** [comment]
@kazlauskis Good news!
"high number of species photo thumbnails"
-> No. Not just sp. photos but habitat photos in the surveys general section. (i hardly used any sp. photos, not more than in 1 or 2 surveys, 1 pic in each) -> BUT NOTE:: can it cause a problem in the SPRING moth surveys where people use photos for authonatic sp. recognition? I think, sp. pics remain in the survey after uploading.
Yes, i still have the old app that doesn't open. Actually, 2 crashed apps on 2 phones (i.e the latest crash+phone and the former crash+phone)I 
 "if you do, we could issue a new app build specifically for you to recover these. "
 -> OK. that is why i kept them untouched
 "Would you be comfortable installing the app as an APK file directly into your device?" 
-> i have never done this before but i think i can do that.
As a lesson learned: you must offer an option to purge the pic / thumbnail dirs from time to time without resetting / renstalling the app and keeping the old surveys (even without the pics or alternatively, not to run into similar overgrowth problems,, just downloading/displaying them fron the online database on demand. -> i raise an issue for this here on github.

**Comment by szabadfalvi** [comment]
@kazlauskis  Also: what happens if you simply delete the thumbnails from the app"s andtoid folder? The too long text string on app startup is still there?

**Comment by kazlauskis** [comment]
The images stored in the internal app folders aren't thumbnails but full-scale photos uploaded to the eBMS system. If you deleted those, then some records couldn't be uploaded. On the other hand, the thumbnails in the local database are only for performance reasons and don't affect the app's core functionality.

**Comment by szabadfalvi** [comment]
> The images stored in the internal app folders aren't thumbnails but full-scale photos uploaded to the eBMS system. If you deleted those, then some records couldn't be uploaded. On the other hand, the thumbnails in the local database are only for performance reasons and don't affect the app's core functionality.

Yes, i know. That is why i only delete them after uploading the respective surveys.
Opening an uploaded survey, it shows the photo thumbnails, which in turn can be tapped to open the full-sized photo.
The full-sized photo is displayed even if you delete the full-sized pics in the App"s files / Pictures folder! I assume, the duplicates from Internal shared storage / Pictures are used then. It is a problem though that pictures taken by the App are always stored in this directory and the App is unaware if you moved your default pictures directory (DCIM) to your SD card. 
A subfolder under the same main folder (Internal shared storage / Pictures / .thumbnails) stores all thumbnails for the phone's apps. You wrote, the crash is caused by the large number of thumbnails.
Does the App generate its own thumbnails or i am missing something?

**Comment by Vilius-Stankaitis** [comment]
Hi,  we have created the app build(267), which deletes all uploaded surveys before the app starts, so it should reduce database size. 

1. Once .apk file is downloaded, double click on it and it should update app version.
2. I suggest to test it on the device that data is less importance.
3. Upload all pending records.
4. Delete the app. 
5. Download current app build(261) from play store.

Please let me know how it goes. 

https://flumensio.sharepoint.com/:u:/s/developers/EdzgWuVKCX1Nmmb9JcHtffkBbD-LgL47by_IQeZuIUUnZw?e=re9rb9

Cheers

**Comment by kazlauskis** [comment]
We have implemented a fix for this which will come out with the next app release.

@szabadfalvi I assume the custom app build to recover your pending records has also worked for you, so I am closing the ticket.

**Comment by szabadfalvi** [comment]
@kazlauskis Yes. thank you, the APK app fix worked in 2 cases on 2 devices:
(1) a Samsung dev. (test scenario) with approx 20 uploaded surveys + 2 mock-up surveys with lots of pictures attached; and
(2) Xiaomi Redmi Note 11 (live salvage scenario, my latest crashed app instance) with approx. 200 uploaded surveys + 10 pending surveys-
It is still not working on my former crashed app instance on Xiaomi Redmi Note 8T with few hundreds of uploaded surveys + 87 pending surveys. The APK app fix manages to start up by purging the uploaded surveys, you can even view your pending surveys for a while (see screenshots) but can never log in to upload them before the app fix crashing.  --> My guess: there are still too many pics attached to those 87 pending surveys.
Questions:
(Q1) If - after backing them up - i delete all survey pics from all affected directories (Internal shared storage / Android / App dir / pictures +  Internal shared storage / Pictures  + Internal shared storage / Pictures / thumbnails), start the app fix, log in to eBMS, copy back some survey pics, upload those few surveys and then close and restart the app fix to purge all finished surveys again, would it help easing the stress on the app database? (i guess, not);
(Q2) Would it be possible to make the APK app fix purge the pics from the pending surveys too? Thus i can log in and upload those surveys: (i can attach pics to 5 surveys, uploading them, purging them and so on).
In any case:, in the meantime I advised all our app users amassing large amount of data to reset their app.
![AppFix_NotWorking-1_Screenshot_2023-06-30_uk ac ceh ebms](https://github.com/BiologicalRecordsCentre/ABLE/assets/93212424/7b07e128-a08d-470b-89be-e09bd7e04e4e)
![AppFix_NotWorking-2_Screenshot_2023-06-30_uk ac ceh ebms](https://github.com/BiologicalRecordsCentre/ABLE/assets/93212424/03f5535d-2c6d-4a45-b774-a0e90ef06739)
